### ISSUE TITLE
Incorrect description for downloading process 

### ISSUE THREAD

**Issue by KR1sis** [ansman/kotshi#13]
Written:
> compile 'se.ansman.kotshi:api:0.3.0'
> kapt 'se.ansman.kotshi:compiler:0.3.0'

Should be
> compile 'se.ansman.kotshi:api:0.3.0-beta1'
> kapt 'se.ansman.kotshi:compiler:0.3.0-beta1'

**Comment by ansman** [comment]
Fixed, thanks.
