### ISSUE TITLE
Treat String as a primitive.

### ISSUE THREAD

**Issue by JakeWharton** [ansman/kotshi#14]
It's a JSON primitive, afterall, and is unlikely to have an adapter unless the property is annotated with a JsonQualifer (thus disqualifying it anyway).

I have this like 90% done locally. Can push to completion if you agree.

**Comment by JakeWharton** [comment]
Got it working. Slightly blocked by the PRs I've already sent.

**Comment by ansman** [comment]
So I considered this but found it more likely that people had created a custom adapter for that than primitives and the fact that no boxing was required made it easier to motivate keeping it like it is today.

But that said I think I do agree that they should probably be treated as primitives. Feel free to add a PR if you have one.

**Comment by JakeWharton** [comment]
All my other PRs royally screwed up my implementation, so i'll probably re-do it from scratch. Not sure when that'll be, so feel free to give it a go.
