### ISSUE TITLE
Generated annotation not found when compiling against Java 11

### ISSUE THREAD

**Issue by tompee26** [ansman/kotshi#173]
When i updated my source/target compatibility to 11, `javax.annotation.processing` package is no longer there. Probably changed to `javax.annotation` only.

**Comment by ansman** [comment]
`javax.annotation.processing.Generated` is available since Java 9.

Which JDK are you using to compile your project and are you setting both the Java and Kotlin target version or only one of them?

**Comment by tompee26** [comment]
I am using JDK 11. I am setting both java and kotlin.

**Comment by ansman** [comment]
Is this Android or just JVM?

**Comment by tompee26** [comment]
This is on Android

**Comment by ansman** [comment]
Can you post the full build error?

**Comment by tompee26** [comment]
I set this sample application up.
https://github.com/tompee26/KotshiJava11Test

**Comment by ansman** [comment]
Sorry for the slow response, I'm still investigating. My preliminary findings are that the Android Gradle Plugin does something which makes it work for generated Java code but it does not work for the Kotlin code.

For now, to become unblocked, you can include the [`javax.annotation-api`](https://mvnrepository.com/artifact/javax.annotation/javax.annotation-api) dependency. Another option is to add an option in Kotshi to disable the generation.

I will file an issue against the Android Gradle Plugin once I can confirm it is at fault.

**Comment by ansman** [comment]
@tompee26 Do you still see this issue?

**Comment by ansman** [comment]
So I've found the root cause of the issue which is that Android does not support Java 11 yet and you won't be able to target Java 11 when compiling. If you change to Java 8 then it'll work as expected.
