### ISSUE TITLE
Investigate if Gson adapters could be generated easily

### ISSUE THREAD

**Issue by ansman** [ansman/kotshi#2]

**Comment by JakeWharton** [comment]
I'm against this as I'd like to see Gson whither away in a slow death. It's blown its complexity and API budget for continued tolerance and historical baggage makes change nearly impossible.

However, this should be trivial as the Moshi APIs currently used by this project were modeled from the best parts of Gson.

I would think it'd go something like this:

 * Rename `@JsonSerializable` to something library-specific (prefix with `Moshi` or `@MoshiJsonAdapter` or `@GenerateJsonAdapter` or whatever).
 * Renamed `@KotshiJsonAdapterFactory` in a similar fashion.
 * Introduce Gson variants of those two annotations.
 * Refactor the processing steps to use an enum which contains various information like:
    * A `ClassName` for the adapter and factory.
    * A `ClassName` for the `JsonReader` and `JsonWriter`.
    * Strings for the various method names.

The generated logic is 99% shared and the enum provides the differently named bits depending on which annotation is present.

**Comment by ansman** [comment]
I agree, I don't think it should be done too. I haven't had any requests for it so I think it could probably be skipped.
