### ISSUE TITLE
Serialisation issue is sallowed 

### ISSUE THREAD

**Issue by nksaroj** [ansman/kotshi#203]
I've noticed we often missed adding the @JsonSerializable attribute and Kotshi silently fails to serialize and never throws an error and we missed to see in the Logcat. It would be great if there is any option to optin.

**Comment by ansman** [comment]
Is this happening every time you compile or only when adding the annotation to new classes?

If it's every time make sure you've added `kapt("se.ansman.kotshi:compiler:<version>")` to that module.

**Comment by ansman** [comment]
I'm closing this for now. Please add a comment if you're stilling seeing this.
