### ISSUE TITLE
Unresolved reference: KotshiAppJsonAdapterFactory

### ISSUE THREAD

**Issue by fendoupi** [ansman/kotshi#204]
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import se.ansman.kotshi.KotshiJsonAdapterFactory
@KotshiJsonAdapterFactory
object AppJsonAdapterFactory : JsonAdapter.Factory by KotshiAppJsonAdapterFactory
![bug](https://user-images.githubusercontent.com/15666063/224257354-da570b2a-39c2-480f-a439-2f922f63e719.png)

**Comment by fendoupi** [comment]
The compiler cannot pass

**Comment by ansman** [comment]
Some questions:
- Did you add the compiler dependency to build.gradle?
- Did you try building the project?

These references will be unresolved until you build once.
