### ISSUE TITLE
Always use the adapter for primitives if JsonQualifiers are present.

### ISSUE THREAD

**Issue by JakeWharton** [ansman/kotshi#23]
There's no reason to annotate a primitive wth a qualifier unless you want an adapter to be used.

**Comment by JakeWharton** [comment]
This is super easy, I just didn't feel like writing tests for it which will take 10x longer than the behavior change.

**Comment by JakeWharton** [comment]
This is fixed. I guess I'll try writing a test for it...

**Comment by JakeWharton** [comment]
And funny enough, I just ran into a case where I need this!

**Comment by ansman** [comment]
Should I cut a new release?

**Comment by JakeWharton** [comment]
That'd be swell!
