### ISSUE TITLE
[Intermittent] No JsonAdapter is getting created for random response classes after migrating to ksp from kapt

### ISSUE THREAD

**Issue by kuldeepyadav1724** [ansman/kotshi#243]
exception: java.lang.IllegalArgumentException: Cannot serialize Kotlin type com.dunzo.payment.http.PaymentPageResponse$PaymentPage$PaymentSection. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapterFactory from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.

@JsonSerializable annotation has been used on PaymentPageResponse and its subclasses as well, but when i check for the generated json Adapter in KotshiApplicationJsonAdapterFactory, jsonAdapter is not present. issue is intermittent and happening for any random response class.
solutions so far we tried: cleaning our project and rebuild again, making ksp.incremental=false
ksp.incremental=false is working 100%.

Android Studio Flamingo | 2022.2.1 Patch 2
Build #AI-222.4459.24.2221.10121639, built on May 12, 2023
Runtime version: 17.0.6+0-17.0.6b802.4-9586694 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    gradle.version.catalogs.dynamic.support=true

library used:
"com.squareup.moshi:moshi:1.15.0"
"se.ansman.kotshi:api:2.11.3"
"se.ansman.kotshi:compiler:2.11.3"

ksp version:
id 'com.google.devtools.ksp' version '1.8.21-1.0.11'
ksp arguments:
ksp {
		arg("kotshi.useLegacyDataClassRenderer", "true")
		arg("kotshi.generatedAnnotation", "javax.annotation.Generated")
}
javaxAnnotation library:
"javax.annotation:javax.annotation-api:1.3.2"

**Comment by ansman** [comment]
Thanks, I'll check incremental ksp support out!

**Comment by abhimaandunzo** [comment]
@ansman any luck on the above?

**Comment by ansman** [comment]
Yup, I believe I found the issue and fixed it in #245 which was release as 2.11.4 this morning.

**Comment by abhimaandunzo** [comment]
thanks @ansman  for quick turn around
