### ISSUE TITLE
[Feature request] Add genParser & genSerializer params to @JsonSerializable

### ISSUE THREAD

**Issue by LouisCAD** [ansman/kotshi#40]
Hi,
Sometimes, a `@JsonSerializable` model is only parsed from Json, or only serialized to Json.
Yet, kotshi generates both `fromJson()` and `toJson()` methods. Since these methods are implementations of an interface, I assume they can't be proguarded, so this ends up being dead code cluttering the final dex.

So my proposal is to add in `@JsonSerializable` either:
- an enum parameter named something like `generateMode` with 3 values: `ALL`, `PARSER` & `SERIALIZER`.
- two `Boolean` parameters named `generateParser` & `generateSerializer`

When the annotation parameter(s) specify to not generate the `toJson()` or `fromJson()` method, kotshi compiler would just throw the result of a new utility method that would return a new `IllegalStateException` in the method that should not be generated.

What are your thoughts on this feature request?

**Comment by ansman** [comment]
@LouisCAD what are the downsides to it being generated? The method won't consume any resources anyway (the method has to be generated anyway because of it being abstract). Adapters are used in both methods or no method so we wouldn't save on that either.

**Comment by LouisCAD** [comment]
@ansman The stub implementation would reduce the dex size compared to the full, unused implementation, which means faster download and app launch, and less consumed size, especially if the app has a lot of JSON models that are only used one way

**Comment by ansman** [comment]
I would like to see some data on how much it increases the size by before considering this feature. It will. I think you will need a lot of objects before it outweighs a single drawable so I'm not sure it's worth spending time on TBH.

**Comment by LouisCAD** [comment]
I admit this is not causing an apk size problem in my apps right now, so you're probably right, that may not be worth spending time on it.

Anyway, I opened an app I released which I migrated to kosthi from moshi-kotlin (THIS was the real improvement, thanks BTW) in the apk analyzer and got some data about the dex sizes of the `fromJson()` and `toJson()` methods (after D8 compilation and proguard-android-optimize):
- In a 17 properties, 1.7KB model, the `fromJson()` is 1.2KB and the `toJson()`, 634B
- In a 4 properties, 667KB model, the `fromJson()` is 369B and the `toJson()`, 228B
- In a 7 properties, 812B model, the `fromJson()` is 632B and the `toJson()`, 315B

Maybe someone with a big app in terms of JSON models count/size/complexity could show some interesting data about how much could be saved by generating only the needed implementations.

**Comment by ansman** [comment]
Interesting, well it would be interesting to know how common it is that you only want serialization or deserialization because not all objects will want just one of them.

**Comment by JakeWharton** [comment]
I, too, am highly skeptical of the benefits here.

Serialization is the less common of the two and it contains very little
code. The strings literals are shared with the deserialization code so they
don't add anything. The methods referenced are finite (maybe 12) which are
shared strings in the dex because the reflection serializers use them. I'd
like to check, but I'd estimate each property costs less than 10 bytes in
serialization code.

And this doesn't bring into account the fact that you'd need really superb
code coverage in integration testing to ensure that you don't accidentally
strip code that is rarely used.

Without some good evidence this is worth it, I think this feature is a bit
too granular and dangerous for the average user.

**Comment by LouisCAD** [comment]
I assume a linter could break compilation when a half generated model is used in another one with the other half generated and could also check against the retrofit interfaces, but I agree such work is probably not worth it, especially considering the string pooling. You'd have to have a lot of Json properties used only one side to see significant benefits.

I'm closing this issue for now. This can always serve as reference if ever needed in the future.
