### ISSUE TITLE
Generic type leads to invalid generated code

### ISSUE THREAD

**Issue by LouisCAD** [ansman/kotshi#41]
Here's an example of type parameterized model:
```kotlin
@JsonSerializable
data class PagedResult<out Data>(val data: List<Data>, val meta: MetaData) {
    @JsonSerializable
    data class MetaData(val total: Int,
                        val count: Int,
                        @Json(name = "per_page")
                        val resultsPerPage: Int,
                        @Json(name = "current_page")
                        val currentPage: Int,
                        @Json(name = "total_pages")
                        val totalPages: Int)
}
```
The generated code attempts to refer to `Data.class` which is incorrect since it's a type parameter.

**Comment by ansman** [comment]
Interesting, I'll take a look!

**Comment by ansman** [comment]
I've confirmed the issue and I know the cause, we simply don't handle generics types as arguments to other generic types. I'll fix that when I have time.

**Comment by LouisCAD** [comment]
@ansman If you can show me how the generated code would look like for my example, I can try to add support for this

**Comment by ansman** [comment]
A PR has been opened in #42

**Comment by ansman** [comment]
This has been fixed and released in beta3
