### ISSUE TITLE
Generated factory type should be package scoped

### ISSUE THREAD

**Issue by JakeWharton** [ansman/kotshi#59]
Hopefully this doesn't prevent consumers from other packages from seeing the `JsonAdapter.Factory` interface...

**Comment by ansman** [comment]
I think this will prevent the code from compiling on Kotlin, the subclass needs to have the same or tighter visibility.

**Comment by ansman** [comment]
Maybe you could do this instead?
```kotlin
@KotshiAdapterFactory
object MyFactory : JsonAdapter.Factory by KotshiMyFactory
```

**Comment by JakeWharton** [comment]
Ah, my usage is `internal` which is probably why it worked when I made the change.

I wonder if
```kotlin
@KotshiJsonAdapterFactory
object MyJsonAdapterFactory : JsonAdapter.Factory by KotshiMyJsonAdapterFactory
```
would work...

Biggest problem is that Kotlin won't recognize the Java as being an `object` so you'd be forced to do `by KotshiMyJsonAdapterFactory.INSTANCE`

**Comment by JakeWharton** [comment]
Hah, yep. Downside of that approach, though, is that you get two instances instead of one. It's fine as-is.
