### ISSUE TITLE
JsonQualifier ignored

### ISSUE THREAD

**Issue by PaulWoitaschek** [ansman/kotshi#65]
Suppose I have the following class and annotation:

```kotlin
import com.squareup.moshi.JsonQualifier
import se.ansman.kotshi.JsonSerializable


@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.FIELD, AnnotationTarget.FUNCTION, AnnotationTarget.PROPERTY_GETTER, AnnotationTarget.PROPERTY_SETTER)
@JsonQualifier  
annotation class MyQualifier

enum class WhatEver{
  A,B
}

@JsonSerializable
class Sample(
  @MyQualifier
  val value: WhatEver
)
```

In this case the generated adapter should pass that annotation to moshi so it can get picked up correctly. However it does not:

```java
  public KotshiSampleJsonAdapter(Moshi moshi) {
    super("KotshiJsonAdapter(Sample)");
    adapter0 = moshi.adapter(WhatEver.class);
  }
```

**Comment by JakeWharton** [comment]
That `Sample` class doesn't compile as-is.

There are tests which show that qualifiers work: https://github.com/ansman/kotshi/blob/1cb6ccc3178851a2a5d1cd3b48851bd0634fce75/tests/src/main/kotlin/se/ansman/kotshi/MultipleJsonQualifiers.kt#L12

**Comment by PaulWoitaschek** [comment]
How does it not compile? For me it compiles?

**Comment by PaulWoitaschek** [comment]
When I remove the `@Target(AnnotationTarget.FIELD, AnnotationTarget.FUNCTION, AnnotationTarget.PROPERTY_GETTER, AnnotationTarget.PROPERTY_SETTER)
`, it gets generated with the correct adapter.

**Comment by JakeWharton** [comment]
Oh I missed the parenthesis. Sounds like Kotlin is defaulting the qualifier to the wrong target then.

**Comment by ansman** [comment]
Try adding `AnnotationTarget.VALUE_PARAMETER` too. Perhaps Kotshi should check the getter for qualifiers too.

**Comment by JakeWharton** [comment]
I'm not a huge fan of that since it requires precedence rules. What happens
if there's one annotation on each? Or two on the param and one on the
getter. Or one property has them on the getter and another on the
parameter. All kinds of edge cases fall out.

**Comment by ansman** [comment]
Closing this, I'll consider adding to the readme that the value parameter needs to be annotated.
