### ISSUE TITLE
Wildcard support for properties

### ISSUE THREAD

**Issue by andanicalik** [ansman/kotshi#67]
Hi. I have json which some keys contains different object arrays like this.
`{
	...
	"keys": [
		{
			"a":1,
			"b":"value"
		},
		{
			"d":"value",
			"e":3.6
		}
	]
}`

data class Example(@Json(name = "keys") var keys: List<Map<String, Any>>)

In Moshi, I can parse like above. But when i try with kotshi it return error -> Kotshi: Properties cannot contain wildcard types.
What should I do for parse json with kotshi?

**Comment by ansman** [comment]
I cannot reproduce this, I added a test case too: https://github.com/ansman/kotshi/commit/454986f428aae69def80f09ef6b18027317290dd

**Comment by NightlyNexus** [comment]
The difference between the issue and the test is the `var` vs. the `val`. You'll probably have to `@JvmSuppressWildcards`.

**Comment by ansman** [comment]
For now you can use `@JvmSuppressWildcards` but Kotshi should handle this.

I'm wondering how this should be handled. Should `? extends Object` (and maybe `? super Object`) be treated as `Object`?

**Comment by ansman** [comment]
And also, should `?` also be treated as `Object`?

**Comment by NightlyNexus** [comment]
Is there a use case for wildcard types besides the original post above?
fwiw, [Moshi will not handle wildcard types in Java in the next update.](https://github.com/square/moshi/commit/a210d89a554a8f9bdd4961162c47ab53bdde52e5)

**Comment by ansman** [comment]
Well, the problem is that Kotlin inserts wildcards everywhere unless you use the annotations. I feel like Kotshi is already forcing too many annotations down your throat, I'd rather avoid requiring even more.

What are the downsides to always using the upper or lower bound?

**Comment by NightlyNexus** [comment]
Besides the Kotlin usage here, they are just always a mistake. If the upperbound type will always be the type used for serialization, the caller should explicitly state that that is the type.

But, agree the Kotlin situation here might make it worthwhile to add leniency in Kotshi.

**Comment by ansman** [comment]
I implemented a fix that treats it as `Object` in #68

@NightlyNexus Feel free to review if you have time, it's not a big PR.
