### ISSUE TITLE
Transient fields are not ignored

### ISSUE THREAD

**Issue by bishiboosh** [ansman/kotshi#78]
Fields marked `@Transient` are not ignored. I'll try to add a PR for this, as the fix seems quite easy (just detect the transient modifier in the parameter, and ignore this parameter if it is the case)

**Comment by gladed** [comment]
If you do this, don't forget to allow setting a default value into the field when deserializing.

**Comment by ansman** [comment]
It’s not that easy I’m afraid since you need all properties to be declared in the constructor. One solution is to enforce default values for transient properties but I’m not sure I like it. It feels a bit like this could be solved in a nicer way (in the client code that is)

**Comment by gladed** [comment]
[Moshi supports transient](https://github.com/square/moshi#omit-fields-with-transient), is there an argument that Kotshi shouldn't?

Consider:
```
@JsonSerializable
data class User(
    val name: String,
    val email: String,
    @Transient val sessionKeys: List<String> = listOf())
```

Yes you could put `sessionKeys` down in a separate property but then you lose out on all the benefits of `data class` for that field including copy constructors, hashing, and equals. And yes one could always model the transient data outside of the data class but that seems restrictive.

**Comment by gladed** [comment]
@bishiboosh hope you don't mind that I gave this a try!

**Comment by bishiboosh** [comment]
@gladed I was on holidays, so thank you ! I'll go check your PR :D

**Comment by gladed** [comment]
Tried it in 1.0.3 and it's working great, thanks for merging @ansman
