### ISSUE TITLE
Stop using adapters for primitive values as default

### ISSUE THREAD

**Issue by ansman** [ansman/kotshi#8]
Using adapters have a couple of downsides:
- Requires fetching the adapter which will go though all the user factories first
- Requires a field for the adapter
- Boxes the primitive

The previous behaviour should still be enabled using annotation options.

**Comment by LouisCAD** [comment]
Hi, is a version with these commits released?

**Comment by ansman** [comment]
Not yet, I have some more things I want done before the next release.
