### ISSUE TITLE
Json Default Value to Lists?

### ISSUE THREAD

**Issue by ademar111190** [ansman/kotshi#80]
Hi guys, what about an annotation to give default values to lists?
Something like:

```
@Target(AnnotationTarget.VALUE_PARAMETER,
        AnnotationTarget.FUNCTION,
        AnnotationTarget.CONSTRUCTOR,
        AnnotationTarget.FIELD,
        AnnotationTarget.PROPERTY_GETTER)
@Retention(AnnotationRetention.SOURCE)
@JsonDefaultValue
annotation class JsonDefaultValueList

@JsonDefaultValueList
fun <T> defaultJsonDefaultValueList() = listOf<T>()
```

**Comment by ansman** [comment]
I don’t really understand this issue, what you describe is already supported, in exactly the same way as in your example

**Comment by ademar111190** [comment]
Sorry I was not clear. 
What I was trying to say is why do not add this feature to the library, in the same way as the library already does with the defaultString and others.
Currently, everyone needs to add this same code to its project, so it is the motivation.

**Comment by ansman** [comment]
I see your point, I need to think about this. One would probably want to name it `JsonDefaultValueEmptyList` and then we need to add the same for sets and maps.

**Comment by ansman** [comment]
Annotation values must be compile time constants so lists are no allowed, otherwise we could simply create a generic annotation that accepts default values for all types.

**Comment by ademar111190** [comment]
I got it.
Given the limitation, I would say the idea to have the empties `list, set, map, etc` is good.

**Comment by JakeWharton** [comment]
Do you want this for all lists or just individual ones? You can write a
generic JsonAdapter for this which will handle all non-null lists
automatically.

And even if you only want some properties to have this behavior, you can
define your own annotation and have the JsonAdapter look for it.

There shouldn't be a need to add explicit support in Kotshi as Moshi has
built-in support for enabling this behavior already.

**Comment by ansman** [comment]
@JakeWharton It wouldn't work doing it in Moshi if you want a default value when the key is absent from the json.

**Comment by JakeWharton** [comment]
It would provided you are delegating to the built-in adapters for primitive
types which I think the library does automatically when a JsonQualifer
annotation is present.

**Comment by ansman** [comment]
If a key is absent from the Json moshi is never queried.

For example given this class:
```
public class Foo {
  public Bar bar;
}
```
and this json:
```
{}
```
the adapter for `Bar` would never be called.

**Comment by JakeWharton** [comment]
True.

**Comment by ansman** [comment]
Closing this, it's no longer relevant when #108 is merged
