### ISSUE TITLE
kotlin-stdlib-jre7 is deprecated

### ISSUE THREAD

**Issue by autonomousapps** [ansman/kotshi#83]
I get the following warning when building my project:
```
kotlin-stdlib-jre7 is deprecated. Please use kotlin-stdlib-jdk7 instead
```

I ran `./gradlew :app:dependencies` and noted that Kotshi is the only library I use that imports the deprecated Kotlin library.

You need to be using Kotlin 1.2.40 to see this deprecation warning.

**Comment by autonomousapps** [comment]
Sure, I can do that. It's just one line to change and I was assuming you can do it much faster than I can, given I need to clone the project, etc etc. However, no problem.

**Comment by autonomousapps** [comment]
Fixed in https://github.com/ansman/kotshi/pull/84

**Comment by NightlyNexus** [comment]
Fwiw, GitHub has a web editor (pencil icon) which I use frequently to make quick, single-file changes.

**Comment by autonomousapps** [comment]
And that is just what I did! :)

**Comment by GladeDiviney** [comment]
Any chance of a release to 1.0.4 so users can have this fix?

**Comment by GladeDiviney** [comment]
Thanks!
