### ISSUE TITLE
Deprecate this library?

### ISSUE THREAD

**Issue by PaulWoitaschek** [ansman/kotshi#92]
Does it make sense to deprecated this library? 

If I understand correctly, as of 1.6.0, moshi does everything this library does, or are there any differences?

**Comment by ansman** [comment]
Well, it's an interesting thought. Thought there are a couple of reasons why I don't think that's needed:
- Kotshi has support for things that the built in support doesn't
  - Non reflective factory
  - Not using adapters for primitive types
  - Support for java classes
- The codegen module has not been battle tested
- Kotshi is free to explore new ideas without having to maintain paradigms that are consistent with Moshi's

Long term this library will probably be deprecated in favor for the codegen module though.

**Comment by PaulWoitaschek** [comment]
Okay then thanks for the great library. It feels like your project was the engine for the adapter generation going upstream :)

**Comment by schatzdesigns** [comment]
Moshi codegen has issues with generic classes

**Comment by ZacSweers** [comment]
@schatzdesigns that's not true. As explained in the bug reports you commented on - your issues were programmer error around Moshi's `Types.newParameteredType` usage.
