### ISSUE TITLE
KotshiApplicationJsonAdapterFactory is missing the types

### ISSUE THREAD

**Issue by nksaroj** [ansman/kotshi#97]
Hi,
kapt is generating the type checks when the models are part of the main android project inside KotshiApplicationJsonAdapterFactory class.
But the models are not included in the type checks when it's imported from another module.

Although I've added kapt for the dependent modules.

**Comment by ansman** [comment]
`kapt` only allows you to process classes in one module at a time, you will need to use one factory per module
